name: CD

on:
  push:
    branches: [master]

jobs:
  docker:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t webhook-pipeline .
